version: "3"

services:
    ui:
      build: ui/.
      ports:
        - "8080:8080"
    app:
      build: scheduling/.
      ports:
        - "3000:3000"
      environment:
        - username="User"
        - password="Pass"
        - SERVER_PORT=3000
    postgres:
      image: postgres:10.5
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      logging:
        options:
          max-size: 10m
          max-file: "3"
      ports:
        - '5432:5432'
      volumes: 
        - ./postgres-data:/var/lib/postgresql/data
        # copy the sql script to create tables
        - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql